In [1]:
import numpy as np

In [81]:
myarray= np.random.randint(0,2,4)
print(myarray)

[0 0 0 1]


define binary shuffle function. for example input_code = [0, 0, 1, 0], ratio = 0.25 which means 1/4 code can be reversed,
then output_code may be[1, 0, 1, 0] or [0, 1, 1, 0] or [0, 0, 0, 0] ....

In [79]:
def shuffle_binary_code(array, ratio):
    tmp = array
    N = len(array)
    M = round(N * ratio)
    import random
    indxs = random.sample(range(0, N), M)
    for indx in indxs:
        tmp[indx] = abs(array[indx] - 1)
        print(indx)
    output = tmp
    tmp = np.zeros(N)
    return output, indxs

In [93]:
myarray= np.random.randint(0,2,4)
print(myarray)
output, indxs = shuffle_binary_code(myarray, 0.8)
print(output, indxs)

[0 1 1 0]
1
2
3
[0 0 0 1] [1, 2, 3]
